### ISSUE TITLE
[Debug Log] Regular Expression Fails to Fully Redact Passwords Containing Quotation Marks

### ISSUE THREAD

**Issue by JanGross** [kepelet/flo#24]
While troubleshooting the login issues with a missing LFM API key, I noticed that the current, although temporary, implementation of redacting passwords fails to handle cases where the password itself includes a quotation mark (").  

This could lead to an unsuspecting user accidentally disclosing their password or part of it, depending on the placement of the quotation mark, when (carelessly ^^) sharing logs.  

**Steps to reproduce:**
- Enable Request Logs
- Enter wrong login credentials with the password `"visible`
- Go to Debug -> All - and copy the Authservice.Login entry
- It will show  `[Body]: {"password":"[REDACTED]"visible","username":"Username"}`

**Affected code:**
https://github.com/kepelet/flo/blob/759c8124b74b36640caed448fc9e5c5f9e22f7c3/flo/Shared/Services/AuthService.swift#L69-L74

**Comment by faultables** [comment]
yeah the current pattern is very problematic — still figuring out how to strip the `body` part since the more important is the headers

**Comment by faultables** [comment]
the regex is updated. i think [it works](https://regex101.com/r/I9ks7a/1) now

**Comment by faultables** [comment]
closing this as of https://github.com/kepelet/flo/discussions/27
