### ISSUE TITLE
Unknown genre

### ISSUE THREAD

**Issue by tehabe** [kepelet/flo#25]
Most if not all of my music doesn't have a genre so, this field is usually empty and flo shows in the album view "unknown genre" instead of showing nothing and just the year.

**Comment by faultables** [comment]
my idea is to keep the consistency — but, hey, i think this looks better

![image](https://github.com/user-attachments/assets/3b13ca98-864e-4dba-a547-9ca0e0a16f5f)

also, there's a possibility that "release year" value is `0` which will show it as "Unknown release year", is it better if we hide that too instead?

**Comment by tehabe** [comment]
Hiding it completely looks usually cleaner than "unknown something"

![Screenshot 2024-11-25 at 14 16 13](https://github.com/user-attachments/assets/2771dc96-1909-4f1e-9a82-2d9519d7e73a)
