### ISSUE TITLE
Idea for the home screen

### ISSUE THREAD

**Issue by tehabe** [kepelet/flo#26]
Instead of a picture and a welcome screen, my idea would be to have the choice of "recently added albums" or "random albums" to be displayed or a defined playlist.

**Comment by faultables** [comment]
it's already discussed [here](https://github.com/kepelet/flo/discussions/15#discussioncomment-10992809) and here is the [current prototype](https://bsky.app/profile/rizaldy.club/post/3lbify4hdck27):

![https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:oeht2lhv6qumiusmtokfi4dk/bafkreiezy54amlqslnmnq7l5nogboqrk3hyrmxvgxa36ccgtcijfywvmsa@jpeg](https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:oeht2lhv6qumiusmtokfi4dk/bafkreiezy54amlqslnmnq7l5nogboqrk3hyrmxvgxa36ccgtcijfywvmsa@jpeg)

**Comment by faultables** [comment]
closing this as of https://github.com/kepelet/flo/discussions/27
